# Site settings
title: Jordy the Poet Dev
email: jordythepoet@gmail.com
description: "For writings about code, comics, cinema and life from a programmer and poet living in Chicago with his beautiful wife and Irish wolfhound/poodle, Buk."
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://wiliajc87.github.io/" # the base hostname & protocol for your site
twitter_username: jordythedev
github_username:  wiliajc87

# Build settings
markdown: kramdown
