# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jordy the Dev
tagline:          "Posts about code, comics, and cinema"
url:              http://wiliajc87.github.io
paginate:         1
baseurl:          http://wiliajc87.github.io/poole/
author:
  name:           Jordy Williams
  url:            https://twitter.com/jordythedev
  email:          jordythepoet@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wiliajc87/
